### ISSUE TITLE
Segmentation fault on Linux-nightly

### ISSUE THREAD

**Issue by Totrock** [fangq/mcx#121]
When using the [latest nightly](http://mcx.space/nightly/linux64/) on Ubuntu 18.04  (or the one from 2021-08-10 and most probably also other versions) I get this:

(base) josef@ubuntu1804:~/MCXStudio/MCXSuite/mcx/bin$ ./mcx
Segmentation fault (core dumped)

It also doesn't have the classic executable symbol in the ubuntu file explorer.
On the other hand mcxlab with octave works for this nightly build.
The bin from the v2020 release is an executable and works fine.
fyi:
(base) josef@ubuntu1804:~/MCXStudio/MCXSuite/mcx/bin$ file mcx
mcx: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), statically linked, stripped

**Comment by fangq** [comment]
I was able to reproduce the issue, it is related to the exe packer, upx, that I used to compress the executable. see this upstream bug: https://github.com/upx/upx/issues/376

after upgrading upx 3.94 in Ubuntu 18.04 to 3.95, the seg fault error is gone. please download nightly build again and verify.

PS: I upgraded the sever running Linux nightly build from Ubuntu 16.04 to 18.04 a few days ago, so the issue was caused by this upgrade.

**Comment by Totrock** [comment]
This works now. Thanks!
