### ISSUE TITLE
Tutorial on how to import arbitrary 3d shapes.

### ISSUE THREAD

**Issue by PyMarc2** [fangq/mcx#189]
Hello,

I would like to use custom 3D shape. Is it possible to import such a shape, providing the 3D model, in any format.
Reading through the [docs](http://mcx.space/wiki/index.cgi?Doc/README), there doesn't seem to be any mention of that, appart from the pre-built shapes.
If not, is it a feature that is planned in the future?

Thank you,

Marc

**Comment by fangq** [comment]
@PyMarc2, importing complex 3D shapes "in any format" is an exceedingly difficult task. Supporting even a single 3D format is not something that can easily done, as it requires finding appropriate libraries and APIs that are compatible/portable with our tool, and then parsing through the shape data structure and rasterize to mcx volume. It is not realistic for mcx.

If you want to import CAD software to define scenes, the closest we have is BlenderPhotonics, which is based on MMC instead of MCX. 

Please see our paper and github repo

https://doi.org/10.1117/1.JBO.27.8.083014
https://github.com/NeuroJSON/BlenderPhotonics

closing this ticket now as it is not realistic to add such kind of support.
