### ISSUE TITLE
pmcx buffer overflow error if bc parameter has 12 characters

### ISSUE THREAD

**Issue by lkeegan** [fangq/mcx#191]
Setting `'bc': '______000010'` gives:
```
*** buffer overflow detected ***: terminated
```
If I remove the last character, `'bc': '______00001'`, then it runs without errors.

**Comment by fangq** [comment]
after checking the code, I found the issue you mentioned here also presents in mcxlab (and mcxcl). Because in mcxlab, I have been using cfg->bc as a NULL-terminating string for printing while in nearly all other places, I only read the first 12 bytes for bc flags.

To avoid issues of mixing use as a string as well as a byte array, I decided to expand the bc[] array in cfg to 13 to allow the ending NULL, https://github.com/fangq/mcx/commit/68db492cfac54e3b792f31eafb56ddbed2639ac7

following this change, I also adjusted mcxlab.cpp and pmcx.cpp to handle the size checking and copying accordingly, see my above tagged commit.

Let me know if you see any problem.
