### ISSUE TITLE
Tissue propoerty for different wavelenght 

### ISSUE THREAD

**Issue by Edouard2laire** [fangq/mcx#196]
Hello, 

I am not sure if this is the correct place to ask but I was wondering if you had any recommendation of the value to use for the tissue property when modeling the head using mcxlab (skin, skull, csf, grey, white matter)?

I see that you wrote some specific value here: https://github.com/fangq/mcx/blob/master/mcxlab/examples/demo_4layer_head.m#L36-L40

Do you have knowledge about how those values change for different simulated wavelengths?  Values used in NIRSTORM are defined here https://github.com/Nirstorm/nirstorm/blob/master/bst_plugin/forward/process_nst_cpt_fluences.m#L597-L622 but only for 3 wavelengths. but I don't have any information for other wavelengths such as 705 nm. 

Thanks a lot, 
Edouard

**Comment by fangq** [comment]
@Edouard2laire, currently mcx relies on users to provide mua/mus/g/n, and does not have the built-in conversion between chromophores or tissue types to mua/mus at specified wavelength.

I do have the plan to incorporate this into mcx at some point, and have been meeting Dr. Steve Jacques and get his help. Steve has some tissue spectral data compiled for his 2013 review paper, which you can download it here:

https://omlc.org/news/dec14/Jacques_PMB2013/index.html
https://omlc.org/news/feb15/generic_optics/index.html

for chromophores->mua/mus, you can use the spectra data from the below link

https://omlc.org/spectra/index.html

or you can call this matlab function from the redbird-m toolbox for mua only

https://github.com/fangq/redbird-m/blob/master/matlab/rbextinction.m

in general, conversion from chromophore to mua is robust, but for different tissue types, it is challenging as 1) there are only sparse data, and 2) different papers show different values for the same tissue type. You will have to make your best judgetment.

**Comment by fangq** [comment]
closing the ticket for now. feel free to reopen if the above reply is not sufficient.

**Comment by Edouard2laire** [comment]
Thank you. 

Do you know how much those values influence the CW fluence estimation? i tried to look at different software and it seems the value used differ quite much. 


![image](https://github.com/user-attachments/assets/e02fa31d-9604-4f80-982e-dff392d592ca)
For example, here is a comparison for grey matter between nirstorn and the nirs-analyizIR toolbox. 

https://omlc.org/software/mc/mcxyz/
seems to provide a function defining the parameter for the different tissues, but it is also different from the previously used value in nirstorm or analyzIR.

**Comment by fangq** [comment]
@Edouard2laire, the "influence" will likely dependent on what quantities you are looking for - such as fluence at a detector, or partial path, or energy deposition, or others. 

this is a known problem, and the optical property values are all over the place in the literature. Our strategy has been making comparisons between a pair of methods using the identically assumed optical properties, such as comparing between DA and MC, MMC vs MCX, layered vs atlas, older head models vs younger atlas models etc. This way, we can largely cancel out the impact due to uncertainties of optical properties.

similarly, I believe many fNIRS software uses ratiometric data, such as those divided/subtracted by the baseline, and only estimate the changes/delta, this way, it also effectively cancel out uncertainties in optical properties. There isn't a reliable answer to this unless a group dedicate their research in characterizing the brain optical tissues and publish something more trustworthy.
