### ISSUE TITLE
MCXLAB : The problem of inconsistency between the calculated optical path length of the trajectory output by mcxlab and the partial length returned by detphoton.ppath

### ISSUE THREAD

**Issue by kurodexue** [fangq/mcx#231]
MCX is a very interesting job, but I encountered problems during its use.

I have a requirement to calculate the maximum depth of each photon. I used a trajectory to calculate it, but there is a problem. The output trajectory should be the scattering point position, incident position, and exit position of each photon, which is also the case in reality. However, its index order is different from the indices of photons in detphoton such as detphoton.v, detphoton.p, and detphoton.ppath. I used Trajectory to manually calculate the path length of photons in a single-layer medium and compared it with the value of detphoton.ppath. The values are the same, but the order of indices is messy. Is it possible for trajectory to output photons in the order of detphoton output?

Thank you!

**Comment by fangq** [comment]
@kurodexue, sorry for the delay

two comments

1. the function you are looking for to sort the trajectory data points by photon ID is mcxplotphotons.m, see https://github.com/fangq/mcx/blob/master/utils/mcxplotphotons.m#L21
2. you can not use photon trajectory data to determine the "maximum depth" (and from which decide maximum penetration depth etc) - photon trajectories are random samples from continuous probability distributions. each trajectory is associated with a probability, and they are not equal. To get any statistically valid numbers, you have to interpret the results in terms of spatial distributions considering all trajectories together (such as the fluence data), instead of individual photon tracks.

For the second point, please see my note in this Jupyter notebook, under the Saving photon trajectories section

https://colab.research.google.com/github/COTILab/MCX24Workshop/blob/master/Training/MCX2024_1C_mcx_command_line.ipynb#scrollTo=Hjhe8m7mNTby

espcially
> 1. a common mistake among users is to treat each photo packet trajectory equivallent to another, as if they are from binary/quantum photons. One must recognize that each simulated photon packet in MCX has different weights and such weight varies along its trajectory. To compute any physically meaningful quantity, one must carefully consider the weighted nature of each trajectory segment. To rigirously process large amount of weight-varying trajectory data can be very time consuming and prone to error.
> 2. a saved photon trajectory is merely a random sample from a continuous distribution of photon distributions; one can not treat such trajectory without considering its stochastic nature - for example, one can not use it to determine the maximum penetration of photon because when you simulate another set of photons, such trajectory will change
> 3. please consider using the volumetric output (fluence-rate, fluence, energy deposition, Jacobian etc) instead of post-processing trajectory data manually. Effectively, the volumetric outputs were derived from such trajectories internally by MCX using GPU parallel threads; they were physically meaningful, unbiased and computed efficiently.
