### ISSUE TITLE
Factor sqrt(2) missing in source type "gaussian"

### ISSUE THREAD

**Issue by bernhardkaplan** [fangq/mcx#25]
Hi,
I think that there is a sqrt(2) missing in line 384 in `mcx_core.cu`:
```cpp
  r=sqrtf(-logf(rand_uniform01(t)))*gcfg->srcparam1.x;
 // should be:
// r=sqrtf(-2 * logf(rand_uniform01(t)))*gcfg->srcparam1.x;
```
as the shape of the sampled Gauss curve has a smaller sigma as expected from the value given to srcparam1.x.
In other words: with the current code, the Gauss curve has a sigma of approx. 1 / sqrt(2) * srcparam1.x, which is contradicting the documentation which says that srcparam1.x is the sigma of the Gauss curve. 
If you run `example/srcbenchmark/run_3benchmark-gaussian.sh`, you get: 
![output_fit](https://cloud.githubusercontent.com/assets/1629580/18128358/97353562-6f85-11e6-94b5-00f9ea04f06d.png)
However, I do not have a math reference supporting the missing sqrt(2) factor.

**Comment by fangq** [comment]
@bernhardkaplan, sorry for the delay. was the beginning of a new semester and had been busy with classes and students.

yes, there is indeed a problem. but let's explain the meaning of srcparam1.x first.

as indicated in https://github.com/fangq/mcx/blob/master/mcxlab/mcxlab.m#L68 , the srcparam1.x in a Gaussian beam denotes the "**waist radius**". 

Based on this document (Fig. 2.1), the beam waist is defined as the 1/(e^2) drop from the peak

http://experimentationlab.berkeley.edu/sites/default/files/MOT/Gaussian-Beam-Optics.pdf

and in this document, you see that the waist has the following relationship to FHWM of a Gaussian:

`2*w=sqrt(2/ln2)*FWHM`

from Eq 8  of this page, 

http://mathworld.wolfram.com/GaussianFunction.html

you can see that for a Gaussian, 

`FWHM = 2*sqrt(2*ln2) sigma`

combining the above two equations, you see that

`w0=2*sigma`   or `sigma=w0/2`

this line (https://github.com/fangq/mcx/blob/42866fadff5e82507de8aecc499f186906d23bdf/src/mcx_core.cu#L385), I should indeed use `sqrt(-2*logf(rand_uniform(t)))` because of the Box-Muller transform 

https://en.wikipedia.org/wiki/Box%E2%80%93Muller_transform

I used it correctly in the Z_GAUSSIAN source, see https://github.com/fangq/mcx/blob/42866fadff5e82507de8aecc499f186906d23bdf/src/mcx_core.cu#L436, but not here. 

According to Box-Muller transform, to generate a Gaussian distribution of variance sigma and mean 0, I can generate a random `R=sqrt(-2*ln(U1))*sigma` and `theta=2*pi*U2`, where U1 and U2 are [0-1] uniform random variables.

Because we know `sigma=w0/2`, replacing into the expression of R, we have

`R=sqrt(-2*ln(U1))*w0/2 = sqrt(-0.5*ln(U1)) *w0`

the above equation is what I should be using in this equation. With this additional sqrt(1/2), you should see that the fitted sigma should be half of srcparam1.x - if srcparam1.x=10, sigma should be 5 instead of 7.611.

On the other hand, for the `Z_GAUSSIAN` source, the srcparam1.x denotes the variance (https://github.com/fangq/mcx/blob/master/mcxlab/mcxlab.m#L91, not the beam waist radius), so, now the R expression should have `sqrt(-2*ln(U))`, as in its current form

https://github.com/fangq/mcx/blob/42866fadff5e82507de8aecc499f186906d23bdf/src/mcx_core.cu#L436

I will commit my above change to close this issue, but feel free to follow up and see if this commit indeed fixed the issue.
