### ISSUE TITLE
make mex

### ISSUE THREAD

**Issue by 4D42** [fangq/mcx#63]
Hi, I have some issue with the `make mex` .

Because mex is also a LateX package I was not able to compile mcxlab.

I had to change this line:
https://github.com/fangq/mcx/blob/7a4c4e5c460550ea20c9596fd6750659453dcca8/src/Makefile#L20

by `MEX=matlab-mex` and it seems to work properly.

I am on linuxMint and I have the package  _matlab-support distro integration for local MATLAB installations_ so maybe it's the problem.

I just wanted to point out this problem so other people can avoid having the same problem. Because at first I didn't understand why you would need LateX to compile the code for matlab. It took me some time to find the problem and the solution....

**Comment by fangq** [comment]
@4D42, I can't find matlab-mex in matlab-support package on Ubuntu. which package does it belong to? On the other hand, I also can not assume such package exist on other distributions such as Fedora or Debian. (I just tried installing matlab-mex and matlab-mex-dev on my Ubuntu 16.04, the installation script asks to modify the name for system gcc. I don't really like this modification and uninstalled those immediately).

From the compilation instructions, I reply on users to set the PATH variable properly in order to invoke matlab or mex. I think this is still the most robust/portable way and does not reply on distribution-specific packages. In light of this, I will label this "wontfix" and close the issue for now, unless this becomes an increasing problem.

But thank you for sharing this workaround.

**Comment by 4D42** [comment]
`matlab-support` is just a package that integrate matlab to the PATH and the desktop menu. So I suppose it add the matlab-mex command. Anyway you are right it's not a global issue.

I was just thinking maybe it is good idea to precise in the Readme file at How to compile MCXLAB  that mex is a matlab function. I know it is say that matlab need to be install and mex need to be in my command PATH. But for me everything was correct matlab was installed (even in the command line) and mex was available in my terminal (ok it was the wrong one... ). That way I opened this "issue"
