### ISSUE TITLE
Errors using a binary volume file with mcx

### ISSUE THREAD

**Issue by kdreher** [fangq/mcx#71]
[mua_and_mus_test.py.zip](https://github.com/fangq/mcx/files/3232992/mua_and_mus_test.py.zip)
I wrote some tests for the simulation, which basically just test the Beer-Lambert law. And I think if mcx uses a binary volume file, there are still some errors:

First, I think the scattering defined in the volume file is not used.
Secondly, I think that the spacing, i.e. the length of one voxel in unit mm, is not accounted for, as well.

I wrote a Python script, which should reproduce and illustrate the errors.

**Comment by fangq** [comment]
hi Kris, thanks for the nice testing script.

Regarding your question on `unitinmm` settings, my student @ShijieYan also found the same recently, and had fixed the problem with a few commit last week, see

https://github.com/fangq/mcx/commit/02efc62ddd084895c63c3ffa7e47eaa2d092afab
https://github.com/fangq/mcx/commit/33df8bf56743b443fd11b4f1f2feca148de5f98d
https://github.com/fangq/mcx/commit/2b907e2707fcb5793bc09794d4e270d94ca0d24b

I am wondering if you can update your mcx and try again. Let me know if the issue remains.

**Comment by fangq** [comment]
I am also curious if you are interested in contributing/expanding this testing script to us so that we can include it in the next release? 

your unittest script looks quite neat. Automatic regression testing is one of the things that I still haven't completed (#11). I think this will be very helpful. Let me know what you think.

**Comment by kdreher** [comment]
Also, yes, I sure would like to contribute an expanded version of the testscript.
I haven't contributed to other big projects yet, so I'm not really sure, how this would work.

**Comment by kdreher** [comment]
I think, I know the problem, that occurs in the functions `test_isotropic_scattering()` and `test_isotropic_scattering_double_width()`. 
In my script, I specified in the json file the two values g=0 since I wanted to simulate isotropic scattering and mus=0 since I want to overwrite it with the values in the binary volume file anyways.

However, in the function `mcx_prepdomain()` in `mcx_utils.c`, the anisotropy is forced to g=1 in regions, where mus=0 is specified in the json file. Therefore, although one has nonzero scattering in the binary volume file, g is set to 1, so that scattering only occurs in a forward manner as if there was no scattering at all.
I changed it to g=0 (to match my test of isotropic scattering) and everything worked properly. (except for the 2-3% deviation described in a previous comment)

I think, there should be an additional condition to test if there is a binary volume file given so that g is not overwritten for all voxel.

**Comment by fangq** [comment]
@kdreher, previously I set g=0 when mus=0, but I g=1 should be more appropriate (and changed it accordingly two years ago, see #51) - if mus=0, that means there is no scattering event in this medium, therefore, whatever direction a photon enters the domain, should continue traveling in the incident direction. A g=1 will allow this behavior.

otherwise, if you have mus=0 and g=0, what kind of behavior do you expect?
